import Head from 'next/head'
import Background from '../components/Background';


const Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Background /> */}
        <section>
          <h1>console.log('ana')</h1>
          <p>
            Lorem ipsum dolor sit amet consectetur adipisicing elit.
            Ipsa molestias dolores delectus. Minima atque,
            error quas tenetur a itaque, odit magni, eum rem aliquam eius
            recusandae esse vero aut nesciunt.
          </p>
        </section>
        <section>
          <h1>follow me, please :)</h1>

        </section>

      </main>
    </>

  )
}

export default Home